CREATE TABLE listings (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    address TEXT NOT NULL UNIQUE,
    city TEXT,
    state TEXT,
    zip TEXT,
    price INTEGER,
    beds INTEGER,
    baths INTEGER,
    sqft INTEGER,
    price_per_sqft INTEGER,
    url TEXT NOT NULL,
    from_collection INTEGER DEFAULT 0,
    source TEXT,
    imported_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    estimated_rent INTEGER,
    rent_yield REAL,
    mls_number TEXT,
    mls_type TEXT,
    tax_information TEXT,
    days_on_compass INTEGER,
    last_updated DATE,
    favorite INTEGER DEFAULT 0,
    year_built TEXT,
    lot_size TEXT,
    hoa_fee TEXT,
    parking TEXT,
    heating TEXT,
    cooling TEXT,
    style TEXT,
    construction TEXT,
    days_on_market TEXT,
    status TEXT,
    agent_name TEXT,
    agent_phone TEXT,
    agent_email TEXT,
    schools_json TEXT,
    price_history_json TEXT,
    walk_score INTEGER,
    transit_score INTEGER,
    bike_score INTEGER,
    walkscore_shorturl TEXT,
    compass_shorturl TEXT,
    latitude REAL,
    longitude REAL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE processed_emails (
    message_id TEXT PRIMARY KEY,
    processed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    label_id TEXT,
    source TEXT
);

CREATE TABLE address_blacklist (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    address TEXT NOT NULL UNIQUE,
    reason TEXT,
    added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    added_by TEXT DEFAULT 'system'
); 